import Foundation
import Termini

/// Belfry's terminal colour theme: the `ThemeStore` choice — a built-in theme,
/// or the user's Ghostty theme (see `GhosttyThemeReader`). Without this,
/// surfaces fell back to libghostty's built-in default, which is why local and
/// remote sessions all looked the same.
///
/// Applied two ways, from the one resolved palette:
/// - as `TerminiTerminalAppearance.theme` — drives the surface's backing colour
///   (visible during live resize) and the light/dark scheme;
/// - as a generated libghostty config snippet loaded into each surface — this is
///   the part that actually recolours the rendered terminal, because Termini's
///   config factory only wires fonts (the C API has no per-colour setter, so
///   colours go in via a loaded config file).
///
/// A program/machine that announces its own colours via OSC still overrides this
/// per surface at runtime, so a host with its own scheme shows through.
enum SurfaceTheme {
    /// The terminal theme for the current `ThemeStore` choice. Read from the
    /// view that builds each surface, so picking a new theme recolours live
    /// surfaces (Termini re-applies a changed theme to a running terminal).
    static var theme: TerminiTerminalTheme {
        let resolved = ThemeStore.shared.current
        return TerminiTerminalTheme(
            id: "belfry-\(ThemeStore.shared.selectedID)",
            name: "Belfry",
            colorScheme: resolved.isDark ? .dark : .light,
            background: .init(hex: resolved.background),
            foreground: .init(hex: resolved.foreground),
            cursor: .init(hex: resolved.cursor),
            selectionBackground: .init(hex: resolved.selectionBackground),
            selectionForeground: .init(hex: resolved.selectionForeground),
            ansiPalette: resolved.palette.map { .init(hex: $0) }
        )
    }

    /// Path(s) to the generated ghostty config snippet that sets the current
    /// theme's colours for newly created surfaces. `[]` if it can't be written
    /// (falls back to ghostty's default — no crash).
    static var configFilePaths: [String] {
        let id = ThemeStore.shared.selectedID
        if let cached = written[id] { return [cached] }
        guard let path = writeSnippet(id: id, resolved: ThemeStore.shared.current) else { return [] }
        written[id] = path
        return [path]
    }

    /// Snippets already written this launch, by theme id.
    private static var written: [String: String] = [:]

    private static func hex(_ value: UInt32) -> String { String(format: "#%06X", value) }

    private static func writeSnippet(id: String, resolved: ResolvedTheme) -> String? {
        let base = AppSupport.directory
            ?? URL(fileURLWithPath: NSHomeDirectory()).appendingPathComponent("Library/Application Support")
        let dir = base.appendingPathComponent("Belfry", isDirectory: true)
        let url = dir.appendingPathComponent("ghostty-theme-\(id).conf")

        var lines = [
            "# Generated by Belfry — terminal colours for the \(id) theme.",
            "background = \(hex(resolved.background))",
            "foreground = \(hex(resolved.foreground))",
            "cursor-color = \(hex(resolved.cursor))",
            "selection-background = \(hex(resolved.selectionBackground))",
            "selection-foreground = \(hex(resolved.selectionForeground))",
        ]
        for (index, color) in resolved.palette.enumerated() {
            lines.append("palette = \(index)=\(hex(color))")
        }
        let text = lines.joined(separator: "\n") + "\n"

        do {
            try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
            try text.write(to: url, atomically: true, encoding: .utf8)
            return url.path
        } catch {
            return nil
        }
    }
}
