import Foundation
import Termini

/// Belfry's terminal colour theme, resolved from the user's Ghostty theme (see
/// `GhosttyThemeReader`) so surfaces match their usual terminal. Without this,
/// surfaces fell back to libghostty's built-in default, which is why local and
/// remote sessions all looked the same.
///
/// Applied two ways, from the one resolved palette:
/// - as `TerminiTerminalAppearance.theme` — drives the surface's backing colour
///   (visible during live resize) and the light/dark scheme;
/// - as a generated libghostty config snippet loaded into each surface — this is
///   the part that actually recolours the rendered terminal, because Termini's
///   config factory only wires fonts (the C API has no per-colour setter, so
///   colours go in via a loaded config file).
///
/// A program/machine that announces its own colours via OSC still overrides this
/// per surface at runtime, so a host with its own scheme shows through.
enum SurfaceTheme {
    private static let resolved = GhosttyThemeReader.resolved

    static let theme = TerminiTerminalTheme(
        id: "belfry-resolved",
        name: "Belfry",
        colorScheme: resolved.isDark ? .dark : .light,
        background: .init(hex: resolved.background),
        foreground: .init(hex: resolved.foreground),
        cursor: .init(hex: resolved.cursor),
        selectionBackground: .init(hex: resolved.selectionBackground),
        selectionForeground: .init(hex: resolved.selectionForeground),
        ansiPalette: resolved.palette.map { .init(hex: $0) }
    )

    /// Path(s) to the generated ghostty config snippet that sets the colours.
    /// `[]` if it can't be written (falls back to ghostty's default — no crash).
    static let configFilePaths: [String] = {
        guard let path = writeSnippet() else { return [] }
        return [path]
    }()

    private static func hex(_ value: UInt32) -> String { String(format: "#%06X", value) }

    private static func writeSnippet() -> String? {
        let base = FileManager.default
            .urls(for: .applicationSupportDirectory, in: .userDomainMask).first
            ?? URL(fileURLWithPath: NSHomeDirectory()).appendingPathComponent("Library/Application Support")
        let dir = base.appendingPathComponent("Belfry", isDirectory: true)
        let url = dir.appendingPathComponent("ghostty-theme.conf")

        var lines = [
            "# Generated by Belfry — terminal colours resolved from your Ghostty theme.",
            "background = \(hex(resolved.background))",
            "foreground = \(hex(resolved.foreground))",
            "cursor-color = \(hex(resolved.cursor))",
            "selection-background = \(hex(resolved.selectionBackground))",
            "selection-foreground = \(hex(resolved.selectionForeground))",
        ]
        for (index, color) in resolved.palette.enumerated() {
            lines.append("palette = \(index)=\(hex(color))")
        }
        let text = lines.joined(separator: "\n") + "\n"

        do {
            try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
            try text.write(to: url, atomically: true, encoding: .utf8)
            return url.path
        } catch {
            return nil
        }
    }
}
